{{- if .Values.certgen.certManager.enabled }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "envoy-oidc-hmac" }}
apiVersion: v1
kind: Secret
metadata:
  name: envoy-oidc-hmac
  namespace: '{{ .Release.Namespace }}'
  labels:
    control-plane: envoy-gateway
  {{- include "eg.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret $existingSecret.data }}
  hmac-secret: {{ index $existingSecret.data "hmac-secret" }}
  {{- else }}
  hmac-secret: {{ randBytes 32 | b64enc | quote }}
  {{- end }}
{{- end }}
